### ISSUE TITLE
Overview store (buyer)

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#37]
You can't see the product of the store, but if you search for it you will find it. We made a product yoghurt and only find it through the search bar

<img width="358" alt="image" src="https://github.com/Lokale-Mand/lokalemand/assets/133126099/47d63a1f-777d-4f8f-96ae-01cf46684ad4">

**Comment by wrteam-vimal** [comment]
Recheck done, Its proper
