### ISSUE TITLE
register page seller, this issue was not solved before

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#42]
Again you can see the string 'store_type' we've mentioned several times that this issue needs to be addressed. It is still not fixed:
![Schermafbeelding 2024-09-12 om 16 52 10](https://github.com/user-attachments/assets/484ec6ff-d572-4da5-9789-b6f0487af123)

@wrteam-vimal

**Comment by wrteam-vimal** [comment]
Solved
