### ISSUE TITLE
Language on register screen seller

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#43]
The categories are in Dutch, while everything else has been English
![Schermafbeelding 2024-09-12 om 17 01 17](https://github.com/user-attachments/assets/e2b5f703-f01b-4c9a-8f64-ece22bc05751)
@wrteam-vimal

**Comment by wrteam-vimal** [comment]
Categories data entry from the admin panel but title and other things manage from the app side language option user need to add data in the same language as per requirement instead of the english only
