### ISSUE TITLE
Example text for adding a product

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#49]
We selected dairy, but the example text is 'Apple'. Would be nice if it was dairy related, it better for the UI-experience

![Schermafbeelding 2024-09-12 om 17 29 01](https://github.com/user-attachments/assets/a9e2ecde-12e7-4c03-95e3-a88b22379759)

@wrteam-vimal

**Comment by wrteam-vimal** [comment]
You can change title, strings anything from here as per your requirements. We just added for the presentation purpose only, you can do changes as per your requirements by follow this video.

https://drive.google.com/file/d/1CztjAXM2t44YDM3B5-UOQmqTIVaL0_1h/view?usp=sharing
