### ISSUE TITLE
Title text: product screen

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#50]
'product description, please?' can be rephrased differently, for example not with ', please?'

![Schermafbeelding 2024-09-12 om 17 29 01](https://github.com/user-attachments/assets/635cd44d-7e08-438d-b187-e3ba9275baac)

**Comment by wrteam-vimal** [comment]
You can change title, strings anything from here as per your requirements. We just added for the presentation purpose only, you can do changes as per your requirements by follow this video.

https://drive.google.com/file/d/1CztjAXM2t44YDM3B5-UOQmqTIVaL0_1h/view?usp=sharing
