### ISSUE TITLE
Profile screen:  Phone number is being shown

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#51]
Why would it be necessary to see the phone number?

![Schermafbeelding 2024-09-12 om 17 35 21](https://github.com/user-attachments/assets/cd588ead-4cda-4c0a-ad8a-0d78ae1059e2)

@wrteam-vimal

**Comment by wrteam-vimal** [comment]
I followed up the design only, if you want to change it we can change it as per your requirement as well.
