### ISSUE TITLE
Account page seller

### ISSUE THREAD

**Issue by amiraeg** [Lokale-Mand/lokalemand#52]
it is not organized, because why is share app under legal?
![Schermafbeelding 2024-09-12 om 17 35 21](https://github.com/user-attachments/assets/798633b3-4952-4c23-8e09-c4ac1b44e9e1)
@wrteam-vimal

**Comment by wrteam-vimal** [comment]
I want proper title and order list 

In which title belongs to which items.

After your share list I can rearrange the whole list.
