### ISSUE TITLE
"view" clickable link on the map screen should be removed. 

### ISSUE THREAD

**Issue by rxbinashley** [Lokale-Mand/lokalemand#9]
The screenshot of the latest app release shows that the shop cards that are listed on the map have a clickable link to view the shop. The clickable link is NOT included in the designs. Please see it for yourselves in the design that I provided.

![IMG_9509](https://github.com/Lokale-Mand/lokalemand/assets/40203570/e0aa944e-c677-4f0d-b6bc-4d31f4e70dff)
![Uploading map.png…]()

**Comment by wrteam-vimal** [comment]
Recheck done, Its proper
